// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scheduler.Api.Data;

#nullable disable

namespace Scheduler.Migrations
{
    [DbContext(typeof(ScheduleDb))]
    partial class ScheduleDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("Scheduler.Data.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Prefix")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Scheduler.Data.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BookingSource")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CheckIn")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CheckOut")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightArrivalNumber")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("FlightArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightDepartureNumber")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("FlightDepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RoomScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("RoomNumber", "ScheduleId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Scheduler.Data.Models.Room", b =>
                {
                    b.Property<int?>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Floor")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Number", "ScheduleId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Scheduler.Data.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Scheduler.Data.Models.Person", b =>
                {
                    b.HasOne("Scheduler.Data.Models.Reservation", "Reservation")
                        .WithMany("People")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Scheduler.Data.Models.Reservation", b =>
                {
                    b.HasOne("Scheduler.Data.Models.Schedule", "Schedule")
                        .WithMany("Reservations")
                        .HasForeignKey("ScheduleId");

                    b.HasOne("Scheduler.Data.Models.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomNumber", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Room");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Scheduler.Data.Models.Room", b =>
                {
                    b.HasOne("Scheduler.Data.Models.Schedule", "Schedule")
                        .WithMany("Rooms")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Scheduler.Data.Models.Reservation", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("Scheduler.Data.Models.Room", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Scheduler.Data.Models.Schedule", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
